version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: muzee-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: muze
    ports:
      - "5432:5432"
    volumes:
      - ./muze_init.sql:/docker-entrypoint-initdb.d/muze_init.sql

  adonis:
    # build:
    #   context: ./muze-back
    #   dockerfile: Dockerfile
    image: registry.nexus.preprod.lab.solutec/felix-sprint-0/back:latest
    container_name: muzee-back-ctn
    environment:
      DB_CONNECTION: pg
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: muze
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3333
      APP_KEY: ${APP_KEY}
      LOG_LEVEL: info
      SESSION_DRIVER: cookie
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    volumes:
      - .env:/app/.env

  react:
    # build:
    #   context: ./muze-front
    #   dockerfile: Dockerfile
    image: registry.nexus.preprod.lab.solutec/felix-sprint-0/front:latest

    container_name: muzee-front-ctn
    ports:
      - "8000:80"

